apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: unit43-net-tls
spec:
  secretName: unit43-net
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: unit43.net
  dnsNames:
    - unit43.net
    - www.unit43.net
